Feature/events tests
krddevdays/backend pull request #11
Opened 2019-04-01 21:49 UTC by sergeibershadsky

2019-04-02 18:50 UTC, TyVik requested changes

2019-04-02 18:50 UTC, TyVik commented on events/factories.py
> +    class Meta:
https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style

2019-04-02 18:50 UTC, TyVik commented on events/tests.py
> +        self.assertTrue(response.data)
Check content, please.

2019-04-12 15:57 UTC, langovoi commented
PR актуальный?

2019-04-12 17:02 UTC, TyVik commented
@sergeibershadsky можешь, плиз, PR обновить? Мы там немного модели попереименовали и в мастер влили.

2019-04-21 16:17 UTC, closed without merging