Feature/events
krddevdays/backend pull request #12
Opened 2019-04-02 18:47 UTC by TyVik

2019-04-09 17:47 UTC, langovoi requested changes
Почти круто и ок, можешь только обьяснить, где-то ты указываешь `null=False`, где-то нет. Какое значение по умолчанию? Думаю везде нужно чтобы в базе было `NOT NULL`.

2019-04-09 17:47 UTC, langovoi commented on events/migrations/0001_initial.py
> +                ('type', django_enumfield.db.fields.EnumField(default=0, enum=events.models.ActivityType)),
Думаю `default=0` не нужен, поле всегда обязательно, но без значения по умолчанию.

2019-04-09 17:47 UTC, langovoi commented on events/migrations/0001_initial.py
> +                ('name', models.CharField(max_length=100)),
Нужно обсудить макс длину строк, возможно, стоит просто решить везде ставить 255 и не париться, либо везде точно решить, почему 100, а не 150.

2019-04-09 18:23 UTC, TyVik commented on events/migrations/0001_initial.py
> +                ('type', django_enumfield.db.fields.EnumField(default=0, enum=events.models.ActivityType)),
Эту настройку стороннее поле определяет. Можно, конечно, переопределить поведение, но большого смысла не вижу.

2019-04-09 18:33 UTC, TyVik commented on events/migrations/0001_initial.py
> +                ('name', models.CharField(max_length=100)),
По мне так не принципиально, т.к. поле модели транслируется в обычное postgres поле varchar. Там если больше 4k, то тогда оно выносится как blob.

2019-04-09 18:34 UTC, langovoi commented on events/migrations/0001_initial.py
> +                ('type', django_enumfield.db.fields.EnumField(default=0, enum=events.models.ActivityType)),
То есть это не default для базы?

2019-04-09 18:44 UTC, langovoi commented on events/migrations/0001_initial.py
> +                ('name', models.CharField(max_length=100)),
То есть это можно не указывать вообще? Может так и сделаем? Иначе не понятно зачем вообще лимит.

2019-04-09 18:51 UTC, TyVik commented
По умолчанию `null=True`. Я пока на это не сильно обращал внимания, т.к. не знаю как в реальности будем использовать. Допустим, модель Event - у неё только имя обязательно, т.к. в самом начале мы не знаем точно даты и места - об этом надо договариваться в процессе. Или Venue - бывает нужно завести новый объект, но всей информации по нему не знаешь. В этом случае я предпочитаю сильно не ограничивать.

2019-04-09 18:52 UTC, TyVik commented on events/migrations/0001_initial.py
> +                ('type', django_enumfield.db.fields.EnumField(default=0, enum=events.models.ActivityType)),
Django в этом плане дебильная - это значение будет подставлено при добавлении записи через фреймворк, но в самой базе этого ограничения нет.

2019-04-09 18:53 UTC, langovoi commented
> Допустим, модель Event - у неё только имя обязательно, т.к. в самом начале мы не знаем точно даты и места - об этом надо договариваться в процессе.

Пока мы добавляем в админке только те события, которые знаем точно. В дальнейшем будем улучшать админку и продумаем как это сделать. Если сейчас сделать поля необязательными - потом сложнее будет мигрировать.

2019-04-09 18:54 UTC, TyVik commented on events/migrations/0001_initial.py
> +                ('name', models.CharField(max_length=100)),
Нужно указать хоть что-то. Для EmailField max_length = 254, для FilePathField = 100.

Ну 100 символов же хватит?

2019-04-09 18:54 UTC, TyVik commented
ok, ограничу.

2019-04-09 18:54 UTC, langovoi commented
> Или Venue - бывает нужно завести новый объект, но всей информации по нему не знаешь

У площадки всегда есть название, адрес и гео-точка. Тут нельзя не знать такие данные.
Зоны - да, но тут они идут связями, так что все ок.

2019-04-09 19:01 UTC, langovoi commented on events/migrations/0001_initial.py
> +                ('name', models.CharField(max_length=100)),
> «Креативный», «тренды» и другие страшные слова. Что должен знать разработчик про дизайн. / Юлия Федоренко

Тут например 105.

2019-04-09 19:02 UTC, langovoi commented on events/migrations/0001_initial.py
> +                ('type', django_enumfield.db.fields.EnumField(default=0, enum=events.models.ActivityType)),
Понял, то есть не для базы. Просто смутило, что это миграция.

2019-04-09 19:02 UTC, TyVik commented
Короче, я ступил - по умолчанию `null=False, blank=False`. Вместо того, чтобы посмотреть в код, я смотрел ограничения в БД. Так что в БД оно nullable, а проверка валидности и пустых значений лежит на Django.

Согласен, хрень. Ещё один повод выкинуть все базы и сделать нормальную поддержку Postgres.

2019-04-09 19:05 UTC, TyVik commented on events/migrations/0001_initial.py
> +                ('name', models.CharField(max_length=100)),
ok, поставлю 255. Мне не жалко :)

2019-04-12 08:41 UTC, langovoi commented
Сейчас есть События, Места, Зоны (внутри Мест) и Активности (внутри Событий).

Активности имеют дата-время начала и конца, тип (для визуализации на фронтенде) и название. По ним можно построить расписание.
Остался нерешённый вопрос как сделать привязку Доклада к Активности. 
На этапе подготовки мероприятия в расписание должен быть просто слот для доклад, а когда доклад уже утверждён, там должна быть ссылка на сущность Доклада.

@binakot @TyVik ваши мысли как это лучше спроектировать?

2019-04-12 08:50 UTC, TyVik commented
Я бы оставил Activity как базовую общую сущность. Доклады собирался делать вообще в отдельной аппе Django, и уже именно у доклада будет линк на слот, который он занимает (связь One2One). Nullable?

2019-04-12 11:08 UTC, langovoi commented
@TyVik опиши пожалуйста подробнее, как это будет создаваться и ты представляешь это будет выводиться.

2019-04-12 11:14 UTC, TyVik commented
Ещё одно приложение talks (каталог talks), в нём пока единственная модель Talk с полем `activity = models.ForeignKey(Activity, null=False, blank=False)`. Тут для обсуждения делать ли её nullable; связывать ли сразу со слотом или привязывать к Событию, а лишь потом раскидывать по слотам.

@langovoi предлагаю уже что-то сделать с этим PR, а обсуждение перевести в новый. Слона надо есть по кускам.

2019-04-12 11:20 UTC, langovoi approved these changes

2019-04-12 11:21 UTC, merged