Набросал схему с докладами для обсуждения.
krddevdays/backend pull request #21
Opened 2019-04-12 18:26 UTC by TyVik

2019-04-14 10:45 UTC, langovoi commented
Я бы не делал для типов вроде обедов и кофе какую-то псевдо-сущность, кажется будет достаточно типа, чтобы визуализировать это.

По докладчику - нужно добавить опционально компанию и должность.

2019-04-14 18:58 UTC, binakot commented
Отпишусь по всему подряд по пунктам.

---

Замечания по UML диграмме, которую выгружал Витя. Возможно, что-то уже не актуально, ну да ладно.

1. `users_user` это системные django пользователи для админки? Просто поля этой таблицы почти один в один с `auth_user`. Чем эти сущности отличаются и зачем каждая из них?

1. Ограничения `VARCHAR` чем-то объяснены? Просто у пароля 128, у логина 150, у имени 30, а у фамилии 150 опять. Тоже самое с адресами и названиями для событий. Похоже на какой-то рандомный набор ограничений. В Postgres уже давно есть тип `TEXT`, который является динамически расширяемым и не требует указывать подобные ограничения.

1. `users_user_user_permissions` пугает своим названием. Может стоит все-таки назвать таблицы с пользователя более понятнее, типа system_users и просто users или что-то типа того.

1. Возможно venue стоит добавить какие-то поле типа описания, чтобы туда можно было что-то написать или вставить ссылку этой площадки/места.

1. В целом, хорошая практика иметь поле "Комментарии" или "Замечания" у сущностей в модели для служебного пользования, там админы смогут оставлять какую-то полезную инфу.

1. У самой сущности `events_event` маловато полей. Но я думаю, вы и так это знаете. Из интересных моментов могу предложить ввести какое-то кодовое название для каждого событий типа KBE4 и прочее. Этим названием можно будет даже пользоваться для роутинга на фронте.

1. Еще мы пока никак не обдумывали, что у события может быть серия мероприятий. Например, Krasnodar Backend это регулярный митап, а Krasnodar Backend 4 - это конкретное событие из серии этих митапов. Но я думаю это сейчас переусложнение, но упомянуть стоит.

1. По поводу `activity`. Джанга не умеет в строковые литераты из enum? Просто мы в java обычно делаем enum вместо номеров захардкоженных, и jdbc это маппит в enum из postgres. Так этот столбец читается на уровне базы, потому что тебе не надо помнить какой номер что означает. И к тому же это более безопасно, т.к. нельзя указать значение, которое не входят в тип, а для чисел никто не мешает написать туда 100500.

1. Сейчас активность кроме типа ничего не имеет, ей нужны поля для специфичных для типа свойств. У доклада это одни поля, у обеда другие. Мы с Витей говорили, он хочет отличительные характеристики джоинить из доп. таблиц. Я так понимаю это встроенно в джангу - если так, то ок. А если это решение ручками делать, то уж лучше пользоваться jsonb столбцами, в которые такие специфичные поля можно писать. По крайней мере мы в java так делаем. Вот мой PoC https://github.com/binakot/Java-Inheritance-Into-PostgreSQL-JSONB-Mapping Но опять же, если джанга из коробки позволяет в наследование через джоин доп. таблиц, то давайте так и сделаем.

---

Теперь по переписке в этом PR. Чет я не понял, какие интерфейсы и моки. У нас есть базовая сущность АКТИВНОСТЬ, тип определяет какие доп. поля у этой сущности будут. Т.е. у нас одноуровневая иерархия. Джоиним по типу нужную доп. таблицу - получаем значения - маппим на объект в джанге.

Возможно, я просто ничего не знаю про питон и джангу (так оно и есть) и вы слово моки используете в другом смысле.

2019-04-14 19:26 UTC, langovoi commented
> Чет я не понял, какие интерфейсы и моки.

Как я понял под моками @TyVik подразумевает вот это место:
https://github.com/krddevdays/backend/blob/2c69d59a44a1f1c8dda07fdd682f84d087689022/events/models.py#L58-L65

2019-04-14 20:29 UTC, TyVik commented
@langovoi Ради унификации интерфейса и работы с ним я бы всё-таки сделал для обедов, кофе-брейков и пр. отдельную сущность.

@binakot спасибо за такое количество комментариев :)
1. `auth_user` быть не должно на схеме. Это стандартная таблица Django для пользователей, которую я переопределил как `users_user`, а удалить у себя забыл.

2. Большинство этих полей определяется в Django. Использование всюду `TEXT` скорее всего вынуждает Postgres выносить поле в TOAST таблицу, что ведёт к потере производительности. В общем, я не вижу смысла останавливаться на их размерах без лишней на то необходимости.

3. Это автогенерируемое название, которое к тому же отражает свою суть. `users_user_user_permissions`: это M2M модель, которая находится в аппе `users` и является полем `user_permissions` у модели `User`.

4. Понадобится - добавим :)

5. O_o добавим при явной необходимости. Пока же, ИМХО, это скорее всего будет мёртвым кодом.

6. Добавим при необходимости.

7. ИМХО, это переусложнение на данном этапе.

8. Из коробки Django не умеет маппить в Postgres enum`ы из-за своей generic сущности. У меня была мысль выкинуть поддержку всех БД, кроме Postgres, и реализовать по-нормальному, но времени и поддержки пока нет. Так что будут циферками.

9. Наследования там не будет, там будет вложенность. Т.е. у активности будет поле, содержащее доп. объект, в котором и будут перечислены специфичные поля. Например, доклад - это должна быть отдельная модель, т.к. у неё будет связанная модель Спикер, она будет участвовать в воркфлоу и пр. Описанный тобой подход используется на моём текущем проекте, и я бы не сказал, что вышло прям очень удобно, хотя такое решение там вполне уместно.

Да, под моками я подразумеваю те сущности, для которых нет моделей в базе, но тем не менее они нужны для единообразия работы с активностями.

2019-04-14 20:54 UTC, binakot commented
2. `TEXT скорее всего вынуждает Postgres выносить поле в TOAST таблицу, что ведёт к потере производительности` не верно. Туда она попадет только в случае превышения размера стандартного столбца. 2 КБ по умолчанию. Но я не настаиваю на типе, я предлагаю везде ставить VARCHAR(255), если нет реальных и объективных причин ставить что-то другое.

9. Ну на уровне базы получается одно и тоже для обоих реализаций, а вот в коде это будет агрегатором вложенным, которые содержит доп. набор полей. Уверен, что джанга умеет собирать сущность из 2х таблиц на базе столбца типа или что-то типа того. Если нет, то нет, пусть будет агрегат.

Остальные пункты - OK.

2019-04-14 20:58 UTC, langovoi commented
> Да, под моками я подразумеваю те сущности, для которых нет моделей в базе, но тем не менее они нужны для единообразия работы с активностями.

@TyVik о каком единообразие ты говоришь? Для обеда и кофе-брейка достаточно только типа, никаких дополнительные данные не нужны как для доклада.

2019-04-14 21:00 UTC, binakot commented
Ну он, скорее всего, говорит про единообразие в коде, потому что ему нужно хранить какой-то вложенный объект. И если не делать моки этих вложенных объектов, то они будут у всех кроме докладов null. А это выглядит как дикий костыль, хотя оно так и есть :)

2019-04-14 21:00 UTC, TyVik commented
> @TyVik о каком единообразие ты говоришь? Для обеда и кофе-брейка достаточно только типа, никаких дополнительные данные не нужны как для доклада.

За заголовком я буду обращаться к `Activity.related_object.title`, а не к `Activity.name`, т.к. заголовок для доклада хранится в отдельной модели => все заголовки будут храниться в отдельных сущностях, которые в общем случае могут и не маппиться в базу.

2019-04-14 21:01 UTC, binakot commented
Смотрите, что нагуглилось первой же ссылкой https://godjango.com/blog/django-abstract-base-class-multi-table-inheritance/

2019-04-14 21:08 UTC, TyVik commented
@binakot 
2. Нет, ограничение в ~2kb даётся на строку, а не на поле - https://habr.com/ru/company/postgrespro/blog/444536/ (искать по слову `2040`). Почему 255?

3. Оставляю как есть.

По ссылке немного не про то. Абстрактные базовые классы в Django создавать можно, но это будут разные таблицы. Соответственно, в расписании мне надо будет делать generic внешний ключ на сущности из разных таблиц. А это может повлечь за собой кучу проблем, начиная от потери консистентности и заканчивая банальным неудобством работы в коде.

2019-04-14 21:10 UTC, TyVik commented
@binakot спасибо за bfy.tw, я умею пользоваться гуглом.

2019-04-15 21:12 UTC, langovoi commented
Давайте уже к чему-то прийдем, нужно ускоряться, осталось две недели.

Предлагаю убрать псевдо-модели для всего, кроме докладов. Совершенно не вижу смысла хранить там какой-то title или что-то подобное.

У спикера должна быть фотография и опциональные поля место работы, должность.
Тут еще стоит решить, как промапать спикера с пользователям сайта (опционально) и не дублировать данные. Это точно нужно будет.

2019-04-16 20:27 UTC, TyVik commented
Если нужно быстро, то от кропов лучше отказаться пока. Самое простое - поле для ввода url картинки.

Раз больше замечаний нет, то продолжаю реализовывать свою идею. Скорее всего завтра и в выходные будет время.

2019-04-19 21:22 UTC, langovoi requested changes

2019-04-19 21:22 UTC, langovoi commented on talks/models.py
> +class Talk(ActivityInterface, models.Model):
Кажется мы можем привязать Доклад к Событию, без активности.
Такое может быть, если мы взяли доклад, но еще не утвердили расписание.

Из этого вытекает, что должна быть возможность по API получить все Доклады для События, либо уметь фильтровать через API Докладов по списку id.

2019-04-19 21:22 UTC, langovoi commented on events/models.py
> +        return f'{self.event} - {self.zone} - {self.start_date}'
А расскажи, зачем это?

2019-04-20 19:46 UTC, langovoi commented on talks/models.py
> +class Talk(ActivityInterface, models.Model):
Решили что сейчас это не горит

2019-04-20 19:47 UTC, langovoi approved these changes

2019-04-21 13:33 UTC, merged