Feature/tickets api
krddevdays/backend pull request #32
Opened 2019-04-28 17:14 UTC by sergeibershadsky

2019-04-28 18:13 UTC, langovoi requested changes

2019-04-28 18:13 UTC, langovoi commented on events/qtickets.py
> +                            }  # if modifier['type'] == 'date'
Давай раскомментируем комментарий, а на модификаторы неизвестного типа нужно кидать ошибку.

2019-04-28 18:13 UTC, langovoi commented on Pipfile
> +coreapi = "*"
Крутая штука, спасибо

2019-04-28 18:22 UTC, TyVik requested changes

2019-04-28 18:22 UTC, TyVik commented on events/qtickets.py
> +        return self.session.request(method=method, url=url, **kwargs).json()
Мне кажется, при каком-нибудь 404 здесь свалится с исключением при конвертации тела ответа в json. Можешь, пожалуйста, проверить?

2019-04-28 18:22 UTC, TyVik commented on events/qtickets.py
> +    def get_seats_url(self, show_id) -> str:
А имеет смысл выносить в отдельный метод генерацию url? Этот и предыдущий очень сильно связаны. Может, пока не разделять?

2019-04-28 18:22 UTC, TyVik commented on events/qtickets.py
> +    is_active = serializers.BooleanField()
Сначала поля, потом метакласс, потом методы. По крайней мере в джанге и её библиотеках.

2019-04-28 18:22 UTC, TyVik commented on events/qtickets.py
> +        super().__init__(data=prepared_data)
Без 100 грамм не разберёшься, а так как я на колёсах, то ничего не понял. Может, имеет смысл сделать мелких функций с говорящими названиями? Например:
```
payments=[
                {'id': payment['id'], 'name': payment['name'], 'type': payment['handler']}
                for payment in show_data['payments']
                if payment['is_active']
            ]
```
Преобразовать в `payments=get_active_payments(show_data),`, а то дебажить это в случае изменения структуры будет весело.

2019-04-28 20:16 UTC, sergeibershadsky commented on events/qtickets.py
> +QTicketsInfo = QTickets()
Хотел предложить, да, но нужно ли сейчас?

2019-04-28 21:35 UTC, sergeibershadsky commented on events/qtickets.py
> +    def get_seats_url(self, show_id) -> str:
Нету уже этого метода )) И нету приватных методов ))

2019-04-29 12:48 UTC, langovoi submitted a review, later dismissed

2019-04-29 18:04 UTC, TyVik submitted a review, later dismissed

2019-04-29 18:04 UTC, TyVik commented on events/qtickets.py
> +    frm = serializers.DateTimeField(required=False)
Смущает именно трёхбуквенное сокращение. Может, как и в других местах что-нибудь типа `start_date`/`finish_date` или `date_from`/`date_to`?

2019-04-29 18:04 UTC, TyVik commented on events/qtickets.py
> +    sales_count_value = serializers.IntegerField(required=False)
Может просто `sales_count`?

2019-04-29 18:04 UTC, TyVik commented on events/qtickets.py
> +    frm = serializers.DateTimeField(required=False)
Заодно и странного кода чуть ниже не понадобится.

2019-04-29 18:06 UTC, langovoi commented on events/qtickets.py
> +    frm = serializers.DateTimeField(required=False)
Это хак, так как тут нельзя указать from, та как это ключевое слово.

2019-04-29 21:07 UTC, langovoi approved these changes

2019-04-30 08:00 UTC, merged