I28
krddevdays/backend pull request #44
Opened 2019-05-11 18:36 UTC by sergeibershadsky

2019-05-11 19:23 UTC, langovoi requested changes

2019-05-11 19:23 UTC, langovoi commented on events/serializers.py
> +    NOT_ACTIVE = 'Ивент не активен в данный момент'
Давай ошибки человечнее сделаем, они же будут отображаться пользователям сайта.

2019-05-11 20:04 UTC, sergeibershadsky commented on events/serializers.py
> +    NOT_ACTIVE = 'Ивент не активен в данный момент'
Предлагай! 🙂

2019-05-11 21:23 UTC, binakot commented on events/serializers.py
> +        raise ValidationError('Неверный ИНН, длинна должна быть 10 или 12 символов', code='inn')
длинна -> длина

2019-05-11 21:23 UTC, binakot commented on events/serializers.py
> +    LEGAL = 'Неверные данные для зказа, ИНН и/или наименование организации не указанны'
зказа -> заказа

2019-05-11 21:23 UTC, binakot commented on events/serializers.py
> +    LEGAL = 'Неверные данные для зказа, ИНН и/или наименование организации не указанны'
указанны -> указаны

2019-05-11 21:23 UTC, binakot commented on events/serializers.py
> +    NOT_ACTIVE = 'Ивент не активен в данный момент'
`Событие неактивно`? Что вообще это состояние значит? Драфт события?

2019-05-11 21:41 UTC, sergeibershadsky commented on events/serializers.py
> +        raise ValidationError('Неверный ИНН, длинна должна быть 10 или 12 символов', code='inn')
Оох, досадная ошибка в великом могучем

2019-05-12 08:12 UTC, TyVik requested changes

2019-05-12 08:12 UTC, TyVik commented on events/serializers.py
> +                not int(self.event_info['is_active'])
`if not(self.event_info['is_active'] and self.current_show['is_active'])`?

2019-05-12 08:12 UTC, TyVik commented on events/serializers.py
> +class QErr:
Вынести в какой-нибудь `constants.py` или `exceptions.py`.

2019-05-12 08:12 UTC, TyVik commented on events/serializers.py
> +    NOT_ACTIVE = 'Ивент не активен в данный момент'
Либо оно уже прошло. Я б разделил эти 2 момента.

2019-05-12 08:12 UTC, TyVik commented on events/serializers.py
> +    MEST_NEMA = 'Для типа {type_id} недостаточно свободных мест'
`Эти билеты уже закончились, попробуйте выбрать другие.`

2019-05-12 08:12 UTC, TyVik commented on events/serializers.py
> +    TICKETS_TYPE_ID_DISABLED = 'Неверный type_id в заказе, {type_id} не доступны для покупки'
`Такие билеты недоступны для покупки.`

2019-05-12 08:12 UTC, TyVik commented on events/serializers.py
> +    TICKETS_TYPE_ID_NONEXISTS = 'Неверный type_id в заказе, {type_id} не существует'
`Продажа таких билетов в данный момент невозможна.`

2019-05-12 08:12 UTC, TyVik commented on events/serializers.py
> +    LEGAL = 'Неверные данные для заказа, ИНН и/или наименование организации не указаны'
`Неверные данные для заказа: ИНН и/или наименование организации не указаны либо не верны.`

2019-05-12 08:12 UTC, TyVik commented on events/serializers.py
> +    TICKETS_EMAIL_NON_UNIQ = 'Email в запросе на покупку билетов не уникальны'
`Email'ы участников должны быть уникальны. На каждый будет отправлен индивидуальный билет.`

2019-05-12 08:12 UTC, TyVik commented on events/serializers.py
> +        # email должны быть уникальны в рамках tickets из данного запроса
Может, вынести в `validate_tickets`?

2019-05-12 08:12 UTC, TyVik commented on events/serializers.py
> +    P_ID_NOT_FOUND = 'Не найден payment_id'
Здесь несколько не в контексте что такое `payment_id`, но пользователь точно не должен знать, что он существует :)

2019-05-12 10:20 UTC, sergeibershadsky commented on events/qtickets.py
> +        return request['data']['payment_url']
✔️

2019-05-12 10:21 UTC, sergeibershadsky commented on events/qtickets.py
> +        if juridicial:
✔️

2019-05-12 10:24 UTC, sergeibershadsky commented on events/serializers.py
> +def check_inn(inn):
✔️

2019-05-12 10:27 UTC, sergeibershadsky commented on events/serializers.py
> +    LEGAL = 'Неверные данные для заказа, ИНН и/или наименование организации не указаны'
✔️

2019-05-12 11:57 UTC, binakot commented on events/serializers.py
> +    P_ID_NOT_FOUND = 'Не найден payment_id'
Согласен, можно писать что-то типа `Не найден идентификатор оплаты` или просто `Не найдена оплата`

2019-05-12 17:56 UTC, langovoi commented on events/qtickets.py
> +        return request['data']['payment_url']
Если `payment_url` нет, значит операция не удалась, нужно кидать ошибку.

2019-05-12 18:25 UTC, TyVik submitted a review, later dismissed
Всё важное поправлено, так что можно вливать.

2019-05-12 18:25 UTC, TyVik commented on events/validators.py
> +    else:
Здесь можно сделать `elif len(inn) == 12:`, а последним `else` вывести `ValidationError`. Но это так, при желании.

2019-05-12 18:50 UTC, langovoi approved these changes

2019-05-12 18:51 UTC, merged