add location Fixes #4
krddevdays/backend pull request #6
Opened 2019-03-31 12:39 UTC by sergeibershadsky

Location model

2019-03-31 14:27 UTC, langovoi commented
Думаю наименование Venue будет лучше описывать модель. А внутри venue - areas

2019-03-31 15:23 UTC, binakot commented
> Думаю наименование Venue будет лучше описывать модель.

Ненавижу слово `venue` и везде пихаю `location`. @langovoi  прав, что этот термин более подходящий для доменной модели, но `location` понятен всем и сразу 😃

2019-03-31 16:36 UTC, TyVik commented
Полез в словарь за переводом слова `Venue`... Давайте всё-таки остановимся на `Location`?

2019-03-31 16:41 UTC, TyVik requested changes

2019-03-31 16:41 UTC, TyVik commented on events/models.py
> +    location = models.ForeignKey('Location', on_delete=models.PROTECT)
No any links to models via string. Pop up `Location` model.

2019-03-31 16:41 UTC, TyVik commented on events/models.py
> +    places = models.ManyToManyField(Place)
No, just ForeignKey to Location in Place. Place can have only one Location.

2019-03-31 16:42 UTC, TyVik commented
Tests for events and activities will be useful :)

2019-03-31 18:39 UTC, TyVik requested changes

2019-03-31 18:39 UTC, TyVik commented on events/models.py
> +    event = models.ForeignKey(Event, on_delete=models.CASCADE)
realted_name was missed.

2019-03-31 18:52 UTC, sergeibershadsky commented on events/models.py
> +    event = models.ForeignKey(Event, on_delete=models.CASCADE)
sorry, will add it now

2019-04-01 06:25 UTC, TyVik approved these changes

2019-04-01 06:25 UTC, merged