Стстус ивента
krddevdays/backend pull request #84
Opened 2019-10-27 23:48 UTC by sergeibershadsky

2019-10-28 07:59 UTC, langovoi commented on users/models.py
> +    draft_viewer = models.BooleanField(default=False)
А можно использовать стандартный механизм permissions?
https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#custom-permissions

2019-10-28 08:00 UTC, langovoi requested changes

2019-10-28 08:00 UTC, langovoi commented on events/interfaces.py
> +    CANCELED = 2
Давай пока без canceled, ещё нужно подумать как это должно влиять на работу системы и пользователей

2019-10-29 06:27 UTC, sergeibershadsky commented on users/models.py
> +    draft_viewer = models.BooleanField(default=False)
Сегодня посмотрю как переделать

2019-10-31 13:35 UTC, langovoi commented on users/models.py
> +    draft_viewer = models.BooleanField(default=False)
пинг

2019-11-01 00:23 UTC, sergeibershadsky commented on users/models.py
> +    draft_viewer = models.BooleanField(default=False)
Сорри, дедлайны подступили, посмотри плз

2019-11-05 19:28 UTC, langovoi commented on events/models.py
> +        permissions = [('view_draft', 'Can view the draft event'), ]
`the draft` => `draft`

2019-11-05 21:35 UTC, sergeibershadsky commented on events/migrations/0012_auto_20191028_0821.py
> +            field=django_enumfield.db.fields.EnumField(default=0, enum=events.interfaces.EventStatusType),
Поменял в миграции чтобы текущие были опубликованы. По дефолту ивент создается черновиком

2020-01-05 10:52 UTC, langovoi approved these changes

2020-01-05 10:53 UTC, merged